apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  labels:
    env: dev
    team: jx
  name: dev
spec:
  kind: Development
  label: Development
  namespace: jx
  previewGitInfo:
    user: {}
  promotionStrategy: Never
  source:
    ref: master
    url: https://github.com/SimpleStepSolutions/environment-wild-turkey-dev.git
  teamSettings:
    appsRepository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
    buildPackName: kubernetes-workloads
    buildPackRef: master
    buildPackUrl: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git
    defaultScheduler:
      kind: ""
      name: ""
    dockerRegistryOrg: simple-step-project
    envOrganisation: SimpleStepSolutions
    gitServer: https://github.com
    helmTemplate: true
    importMode: YAML
    kubeProvider: gke
    pipelineUsername: jenkinsx-bot-sss
    promotionEngine: Prow
    prowEngine: Tekton
    quickstartLocations:
    - excludes:
      - WIP-*
      gitKind: github
      gitUrl: https://github.com
      includes:
      - '*'
      owner: jenkins-x-quickstarts
    storageLocations:
    - bucketUrl: gs://wild-turkey-lts-7756d6c1-938a-48c2-84da-a9300b8c2c2a
      classifier: default
    - bucketUrl: gs://wild-turkey-lts-7756d6c1-938a-48c2-84da-a9300b8c2c2a
      classifier: logs
    useGitOps: true
    versionStreamUrl: https://github.com/jenkins-x/jenkins-x-versions.git
  webHookEngine: Prow
status: {}
